name: Manual Scrape to TXT

on:
  workflow_dispatch: # 仅手动触发

permissions:
  contents: write # 必须赋予写入权限以更新 999.txt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Scraper
        run: python scraper.py

      - name: Commit 999.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Manual-Bot"
          git add 999.txt
          # 只有在文件内容确实有变化时才提交，避免报错
          git diff --quiet && git diff --staged --quiet || (git commit -m "更新号码库: $(date)" && git push)
